default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: 
  password: 
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
development:
  <<: *default
  database: chat
test:
  <<: *default
  database: chat
production:
  <<: *default
  database: chat